MapProject/Models/Leg.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MapProject.Models
{
        public class Leg
        {
// Primary Key
        [Key]
        public int LegId { get; set; }

// Leg #
        public int LegNumber { get; set; }

// Distance
        public double Distance { get; set; }

// Vertical
        public double Vertical { get; set; }

// Munter Rate
        public double MunterRate { get; set; }

// Time
        public double Time { get; set; }

// Created At / Updated At
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

// Foreign Keys
        public int UserId { get; set; }
        public int TourId { get; set; }

// Nav Props
        public User LegCreator { get; set; }
        public Tour RelatedTour { get; set; }
        }
}

MapProject/Controllers/LegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MapProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MapProject.Controllers
{
    public class LegController : Controller
    {
// v~~ S E T U P   V I E W S ~~v //
    // Context (delete ILogger)
        private MapProjectContext db;
        public LegController(MapProjectContext context)
        {
            db = context;
        }
    // Convert current user in Session to uid
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("userId");
            }
        }
    // Returns true or false if current user is logged in
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }
// v~~ M A I N   V I E W S ~~v //
    // Create Leg -> Add to Db
        [HttpPost("add-leg/{TourId}")]
        public IActionResult AddLeg(Leg newLeg, int TourId)
        {
            if (ModelState.IsValid)
            {
                newLeg.UserId = (int)uid;
                newLeg.TourId = TourId;

                // Metric -> Imperial Conversions
                double DistanceKm = newLeg.Distance * 1.609344;
                double VerticalM = newLeg.Vertical * 0.304800609601;

                // Munter Time Calculation
                newLeg.Time = (DistanceKm + (VerticalM / 100)) / newLeg.MunterRate;

                db.Legs.Add(newLeg);
                db.SaveChanges();
                return RedirectToAction("TourDetails"); 
            }
            return View("TourDetails", newLeg);
        }
    // Delete Leg
        [HttpGet("delete/leg/{LegId}")]
        public IActionResult DeleteLeg(int LegId)
        {
            Leg LegToDelete = db.Legs.FirstOrDefault(l => l.LegId == LegId);
            db.Legs.Remove(LegToDelete);
            db.SaveChanges();
            return RedirectToAction("TourDetails", "Tour");
        }
//<~~ E N D   O F   M A I N   V I E W S ~~> //
    }
}

MapProject/Views/Leg/_AddLeg.cshtml
@model Leg
<div class="container mt-5">
    <div class="row justify-content-between">
        <div class="col-6">
            <h3 class="ml-3 text-primary">Add Legs</h3>
                <form class="border border-primary bg-light shadow-lg p-3 mb-5 rounded"
                    asp-action="AddLeg"
                    asp-controller="Leg"
                    method="POST">

                <div class="form-group">
                    <label for="Distance">Distance: </label>
                    <input class="form-control" asp-for="Distance">
                    <small id="errors" class="form-text text-danger">
                        <span asp-validation-for="Distance"></span>
                    </small>
                </div>

                <div class="form-group">
                    <label for="Vertical">Vertical: </label>
                    <input class="form-control" asp-for="Vertical">
                    <small id="errors" class="form-text text-danger">
                        <span asp-validation-for="Vertical"></span>
                    </small>
                </div>

                <div class="form-group">
                    <label for="MunterRate">Rate: </label>
                    <input class="form-control" asp-for="MunterRate">
                    <small id="errors" class="form-text text-danger">
                        <span asp-validation-for="MunterRate"></span>
                    </small>
                </div>

                    <button class="btn btn-primary mt-3" type="submit">Add Leg</button>
                </form>
        </div>

        <div class="col-6">
            <h3 class="ml-3 text-primary">Information</h3>
            <div class="card border border-primary bg-light shadow-lg p-3 mb-5 rounded">
                <p>- Distance is in in Miles.</p>
                <p>- Vertical is a positive number in Feet.</p>
                <p>Common Munter Rates:</p>
                <ul>
                    <li>Off trail travel: 2</li>
                    <li>Uphill travel on foot: 4</li>
                    <li>Flat travel on foot: 6</li>
                    <li>Downhill travel on foot: 8</li>
                </ul>
                <p>Formula:</p>
                <p>time = (distance + (elevation / 100)) / rate</p>
            </div>
        </div>
    </div>
</div>