MapProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MapProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace MapProject.Controllers
{
    public class HomeController : Controller
    {
// v~~ S E T U P   V I E W S ~~v //
    // Context (delete ILogger)
        private MapProjectContext db;
        public HomeController(MapProjectContext context)
        {
            db = context;
        }
    // Convert current user in Session to uid
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("userId");
            }
        }
    // Returns true or false if current user is logged in
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }
// v~~ L O G I N   &   R E G   V I E W S ~~v //
    // Register Page -> Register Form
        // Displayed on Index Page

    // Register -> Create User in Db
        [HttpPost("register")]
        public IActionResult Register(User newUser)
        {
            if(ModelState.IsValid)
            {
                if(db.Users.Any(u => u.Email == newUser.Email))
                {
                    ModelState.AddModelError("Email", "Email already registered, please login.");
                    return View("Index");
                }
                Microsoft.AspNetCore.Identity.PasswordHasher<User> Hasher = new PasswordHasher<User>();
                newUser.Password = Hasher.HashPassword(newUser, newUser.Password);
                db.Users.Add(newUser);
                db.SaveChanges();
                HttpContext.Session.SetInt32("userId", newUser.UserId);
                HttpContext.Session.SetString("userFirstName", newUser.FirstName);
                return RedirectToAction("Dashboard", newUser.UserId); 
            }
            return View("Index");
        }
    // Login Page -> Login Form
        // Displayed on Index Page

    // Login -> Validate LoginUser
        [HttpPost("process-login")]
        public IActionResult Login(LoginUser loginUser)
        {
            if(ModelState.IsValid)
            {
                var userInDb = db.Users.FirstOrDefault(u => u.Email == loginUser.LoginEmail);
                if(userInDb == null)
                {
                    ModelState.AddModelError("LoginEmail", "Invalid email address. Please try again or register.");
                    return View("Index");
                }
                var hasher = new PasswordHasher<LoginUser>();            
                var result = hasher.VerifyHashedPassword(loginUser, userInDb.Password, loginUser.LoginPassword);
                if(result == 0)
                {
                    ModelState.AddModelError("LoginPassword", "Invalid passowrd. Please try again or register.");
                    return View("Index");
                }
                HttpContext.Session.SetInt32("userId", userInDb.UserId);
                HttpContext.Session.SetString("userFirstName", userInDb.FirstName);
                return RedirectToAction("Dashboard", userInDb.UserId); 
            }
            return View("Index");
        }
// v~~ M A I N   V I E W S ~~v //
    // Index Page -> Login & Reg Forms
        [HttpGet("")]
        public IActionResult Index()
        {
            return View("Index");
        }
    // Dashboard Page -> All Tours Summary
        [HttpGet("dashboard")]
        public IActionResult Dashboard()
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            List<Tour> AllTours = db.Tours
                .Include(l => l.Legs)
                .OrderBy(n => n.TourName)
                .ToList();
            return View("Dashboard", AllTours);
        }
    // To Do Page -> Things To Do
        [HttpGet("todo")]
        public IActionResult ToDo()
        {
            return View("ToDo");
        }
    // Logout -> Clear Session
        [HttpGet("logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
//<~~ E N D   O F   M A I N   V I E W S ~~> //
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MapProject/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MapProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MapProject.Controllers
{
    public class TourController : Controller
    {
// v~~ S E T U P   V I E W S ~~v //
    // Context (delete ILogger)
        private MapProjectContext db;
        public TourController(MapProjectContext context)
        {
            db = context;
        }
    // Convert current user in Session to uid
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("userId");
            }
        }
    // Returns true or false if current user is logged in
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }
// v~~ M A I N   V I E W S ~~v //
    // Tour Details Page -> View & Add Legs
        [HttpGet("tour/{TourId}")]
        public IActionResult TourDetails(int TourId)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }
            Tour thisTour = db.Tours
                .FirstOrDefault(t => t.TourId == TourId);

            List<Leg> RelatedLegs = db.Legs
                .Include(t => t.RelatedTour)
                .Where(t => t.TourId == TourId)
                .ToList();
            ViewBag.RelLegs = RelatedLegs;

            return View("TourDetails", thisTour);
        }
    // Create Tour -> Add to Db
        [HttpPost("add-tour")]
        public IActionResult CreateTour(Tour newTour)
        {
            if (ModelState.IsValid)
            {
                newTour.UserId = (int)uid;

                db.Tours.Add(newTour);
                db.SaveChanges();
                return RedirectToAction("TourDetails", new { TourId = newTour.TourId }); 
            }
            return View("Dashboard", "Home");
        }
    // Delete Tour
        [HttpGet("delete/tour/{TourId}")]
        public IActionResult DeleteTour(int TourId)
        {
            Tour TourToDelete = db.Tours.FirstOrDefault(t => t.TourId == TourId);
            db.Tours.Remove(TourToDelete);
            db.SaveChanges();
            return RedirectToAction("Dashboard", "Home");
        }
//<~~ E N D   O F   M A I N   V I E W S ~~> //
    }
}

MapProject/Views/Home/Dashboard.cshtml
@model List<Tour>

<div class="container">
    <h3 class="text-primary">Tour Plans</h3>
    <div class="row border border-primary bg-light shadow-lg mb-5 rounded">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col-3">Tour Name</th>
                    <th scope="col-2">Total Dist</th>
                    <th scope="col-2">Total Vert</th>
                    <th scope="col-2">Total Est. Time</th>
                    <th scope="col-1">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Tour t in Model)
                {
                <tr>
                    <td><a asp-action="TourDetails" asp-controller="Tour" asp-route-TourId="@t.TourId">@t.TourName</a></td>
                    <td>@t.TotalDist() Miles</td>
                    <td>@t.TotalVert() Feet</td>
                    <td>@t.TotalEstHours() Hours  @t.TotalEstMins() Minutes</td>
                    <td><a class="text-danger" asp-action="DeleteTour" asp-controller="Tour" asp-route-TourId="@t.TourId">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg></a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

    @{
        Tour newTour = new Tour();
    }
    <partial name="/Views/Tour/_NewTour.cshtml" model="@newTour"/>

MapProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Login & Registration";
}

<div class="container">
    <h2 class="text-center text-primary">Welcome.</h2>
    <hr>

    <div class="row">
        <div class="col-md">
            <partial name="_Register"/>
        </div>
        <div class="col-md">
            <partial name="_Login"/>
        </div>
    </div>
</div>

MapProject/Views/Home/ToDo.cshtml
<div class="container">
    <h3 class="text-primary">To Do List:</h3>
    <div class="card border border-primary bg-light shadow-lg p-3 mb-5 rounded">
        <ul>
            <li>On Tour delete, delete all associated Legs</li>
            <li>Add Map Functionality</li>
            <li>Add multiple User functionality: Join, Individual Pages, Edit, etc.</li>
        </ul>
    </div>
</div>

MapProject/Views/Home/_Login.cshtml
@model LoginUser

<div class="form border border-primary bg-light p-1 shadow-lg p-3 mb-5 rounded diplay-inline-flex">
    <h3 class="text-center">Login</h3>
    <hr class="border-primary" />
    <form asp-action="Login" asp-controller="Home" method="POST">
    <div class="form-group">
        <label for="LoginEmail">Email: </label>
        <input class="form-control" asp-for="LoginEmail" value="gary@@newmey.com">
        <small id="errors" class="form-text text-danger"><span asp-validation-for="LoginEmail"></span></small>
    </div>
    <div class="form-group">
        <label for="LoginPassword">Password: </label>
        <input class="form-control" asp-for="LoginPassword" value="password">
        <small id="errors" class="form-text text-danger"><span asp-validation-for="LoginPassword"></span></small>
    </div>
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
</div>

MapProject/Views/Home/_Register.cshtml
@model User

<div class="form border border-primary bg-light p-1 shadow-lg p-3 mb-5 rounded diplay-inline-flex">
    <h3 class="text-center">Register</h3>
    <hr class="border-primary" />
    <form asp-action="Register" asp-controller="Home" method="POST">
        <div class="form-group">
            <label for="FirstName">First Name: </label>
            <input class="form-control" asp-for="FirstName">
            <small id="errors" class="form-text text-danger"><span asp-validation-for="FirstName"></span></small>
        </div>
        <div class="form-group">
            <label for="LastName">Last Name: </label>
            <input class="form-control" asp-for="LastName">
            <small id="errors" class="form-text text-danger"><span asp-validation-for="LastName"></span></small>
        </div>
        <div class="form-group">
            <label for="Email">Email: </label>
            <input class="form-control" asp-for="Email">
            <small id="errors" class="form-text text-danger"><span asp-validation-for="Email"></span></small>
        </div>
        <div class="form-group">
            <label for="Password">Password: </label>
            <input class="form-control" asp-for="Password" value="password">
            <small id="errors" class="form-text text-danger"><span asp-validation-for="Password"></span></small>
        </div>
        <div class="form-group">
            <label for="PasswordConfirm">Confirm Password: </label>
            <input class="form-control" asp-for="PasswordConfirm" value="password">
            <small id="errors" class="form-text text-danger"><span asp-validation-for="PasswordConfirm"></span></small>
        </div>
    <button class="btn btn-primary" type="submit">Register</button>
    </form>
</div>